upstream frontend {
    # Apunta al puerto interno 80 del contenedor de producción de React
    server front:80;
}

upstream backend {
    # Apunta al puerto interno 3000 del contenedor de NestJS
    server back:3000;
}

server {
    listen 80;
    server_name localhost;

    # Frontend estático optimizado
    location / {
        proxy_pass http://frontend;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "upgrade";
        proxy_set_header Host $host;
    }

    # Endpoints del API REST
    location /api {
        rewrite ^/api/(.*)$ /$1 break;
        proxy_pass http://backend;
        proxy_http_version 1.1;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    }

    location /socket.io/ {
        proxy_pass http://backend;
        proxy_http_version 1.1;
        
        # Estas cabeceras son OBLIGATORIAS para WebSockets
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "upgrade";
        proxy_set_header Host $host;
        proxy_cache_bypass $http_upgrade;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    }
}