name: Lint

on:
  pull_request:
  # push:
  #   branches:
  #     - main

jobs:
  lint-back:
    name: Lint Backend (NestJS)
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 24
          cache: 'yarn'
          cache-dependency-path: 'back/yarn.lock'

      - name: Install dependencies (backend)
        working-directory: back
        run: yarn install --frozen-lockfile

      - name: Run lint (backend)
        working-directory: back
        run: yarn lint

  lint-front:
    name: Lint Frontend (React + Vite)
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 24
          cache: 'npm'
          cache-dependency-path: 'front/package-lock.json'

      - name: Install dependencies (frontend)
        working-directory: front
        run: npm ci

      - name: Run lint (frontend)
        working-directory: front
        run: npm run lint